spring:
  application:
    name: auth-service

server:
  port: 5000
  context-path: /uaa

#Microservice passwords
password:
  user-service: userServicePassword
  story-service: storyServicePassword
  group-service: groupServicePassword

# Logging configuration
logging:
  level:
    org.springframework: INFO
    gr.personal.auth: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: auth-service.logs

# Increase the Hystrix timeout to 10s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
