spring:
  application:
    name: user-service

feign:
  hystrix:
    enabled: true

# Increase the Hystrix timeout to 30s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
server:
  port: 1001

logging:
  level:
    org.springframework.web: INFO
    gr.personal.story: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: user-service.logs