spring:
  application:
    name: user-service

server:
  port: 1001

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: userServicePassword
      accessTokenUri: http://auth-service:1002/uaa/oauth/token
      grant-type: client_credentials
      scope: server

logging:
  level:
    org.springframework.web: INFO
    gr.personal.story: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: user-service.logs

# Increase the Hystrix timeout to 10s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
