spring:
  application:
    name: discovery-server

server:
  port: 8761
security:
  user:
    password: passw0rd!

eureka:
  client: #Do not register with 'itself'
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0 #WARNING: Remove from production use!!

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://user:passw0rd!@127.0.0.1:8762/eureka/ #peer2 URL

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://user:passw0rd!@127.0.0.1:8761/eureka/ #peer1 URL
