spring:
  application:
    name: monitoring
server:
  port: 8179

turbine:
  aggregator:
    clusterConfig: STORY-SERVICE,USER-SERVICE,GROUP-SERVICE
  appConfig: STORY-SERVICE,USER-SERVICE,GROUP-SERVICE
  combineHostPort: true
