spring:
  application:
    name: edge-server

server:
  port: 8765

endpoints:
  restart: #.../restart restart the application
    enabled: true
  shutdown: #.../shutdown allows for gracefully shutdown of the application
    enabled: true
  health: #../health allows for health checks of the app
    sensitive: false

# Increase the Hystrix timeout to 10s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

zuul:
  # socket timeout: 3.33 minutes connect timeout: 0.33 minutes
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 200000
  #All services will be mapped under the /api URI
  prefix: /api
    #Disable all auto-registering services from Eureka
  ignoreServices: '*'
  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders: Cookie, Set-Cookie
    story-service:
      path: /story-service/**
      serviceId: story-service
      strip-prefix: false
      sensitiveHeaders: Cookie, Set-Cookie
    user-service:
      path: /user-service/**
      serviceId: user-service
      strip-prefix: false
      sensitiveHeaders: Cookie, Set-Cookie
    group-service:
      path: /group-service/**
      serviceId: group-service
      strip-prefix: false
      sensitiveHeaders: Cookie, Set-Cookie

