spring:
  application:
    name: edge-server

server:
  port: 8765

endpoints:
  restart: #.../restart restart the application
    enabled: true
  shutdown: #.../shutdown allows for gracefully shutdown of the application
    enabled: true
  health: #../health allows for health checks of the app
    sensitive: false

# Increase the Hystrix timeout to 30s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

zuul:
    #All services will be mapped under the /api URI
  prefix: /api
    #Disable all auto-registering services from Eureka
  ignoreServices: '*'
  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      stripPrefix: false
    story-service:
      path: /story/**
      serviceId: story-service
      strip-prefix: false
    homepage-service:
      path: /homepage/**
      serviceId: user-service
      strip-prefix: false
    administrative-service:
      path: /administrative/**
      serviceId: user-service
      strip-prefix: false

  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 200000

    #manual expose certain services
#    ex: routes everything under /api/microservice1/... to microservice1 service defined in eureka
#    routes:
#      microservice1:
#        path: /microservice1/**
#        serviceId: microservice1


